apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpf-deployment
  namespace: cpf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpf
  template:
    metadata:
      labels:
        app: cpf
    spec:
      containers:
        - name: cpf
          image: dellabeneta/cpf:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"